---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./audiobookshelf/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./namespace.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
