---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./fasten/ks.yaml
  - ./filebrowser/ks.yaml
  - ./hajimari/ks.yaml
  - ./namespace.yaml
  - ./paperless-ngx/ks.yaml
  - ./syncthing/ks.yaml
  - ./vaultwarden/ks.yaml
